import {Match,MAP,WEAPONS,canBuy} from './sim.js';
import {killFeed,updateEquipment,updateDeath,scopeOverlay} from './combat-ui.js';
import {ArenaRenderer} from './render.js';
import {BattleAudio} from './audio.js';
import {LanClient} from './network.js';
import {loadCharacters} from './character-v2.js';
import {loadViewModels} from './viewmodel.js';
import {assetLoading} from './asset-loading.js';
import {loadingScreen} from './loading-screen.js';
import {declareEnvironmentAssets} from './environment-v2.js';

const $=s=>document.querySelector(s), canvas=$('#arena'), audio=new BattleAudio(),staticMode=document.body.dataset.static==='true';
loadingScreen.markStarted();declareEnvironmentAssets(MAP);assetLoading.subscribe(state=>loadingScreen.update(state));
if(staticMode){$('[data-mode="lan"]').hidden=true;}
let view,match=null,snapshot=null,selfId=null,client=null,mode='offline',team=0,room=null,hostId=null;
let paused=true,active=false,lockFallback=false,lastEvent=-1,lastTime=0,lastHud=0,lastNet=0,frameTime=performance.now(),accumulator=0,noticeUntil=0,damageUntil=0,hitUntil=0,lastResult=false;
let buyOpen=false,scopeLevel=0,resumeScope=0,scopeResumeAt=0,lastAlive=true;
const keys=new Set(),input={forward:0,strafe:0,yaw:0,pitch:0,fire:false,altFire:false,aim:false,jump:false,reload:false,weapon:0,walk:false,crouch:false};
const touch={forward:0,strafe:0,fire:false,aim:false,jump:false};
const mobile=matchMedia('(pointer: coarse)').matches;document.body.classList.toggle('mobile',mobile);
const prefs=(()=>{try{return JSON.parse(localStorage.getItem('freight-fire-settings')||'{}')}catch{return {}}})();
for(const key of ['nickname','quality','size','difficulty'])if(prefs[key])$('#'+key).value=prefs[key];
function savePrefs(){try{localStorage.setItem('freight-fire-settings',JSON.stringify(Object.fromEntries(['nickname','quality','size','difficulty'].map(k=>[k,$('#'+k).value]))))}catch{}}
function status(message,error=false){$('#status').textContent=message;$('#status').classList.toggle('error',error);}
function notice(message,seconds=2){$('#notice').textContent=message;noticeUntil=performance.now()+seconds*1000;}
function me(){return snapshot?.players.find(p=>p.id===selfId);}
function resetScope(){scopeLevel=0;resumeScope=0;scopeResumeAt=0;input.aim=false;}
function neutral(){keys.clear();mouseFire=false;mouseAim=false;dragging=false;Object.assign(input,{forward:0,strafe:0,fire:false,altFire:false,aim:false,jump:false,reload:false,walk:false,crouch:false});Object.assign(touch,{forward:0,strafe:0,fire:false,aim:false,jump:false});client?.sendInput(input);}
function combatInput(){return {...input,pitch:Math.max(-1.45,Math.min(1.45,input.pitch+(view?.recoilPitch||0))),yaw:input.yaw+(view?.recoilYaw||0)};}
function equipSlot(slot){const p=me();if(!p?.alive)return;const weapon=[p.primaryWeapon??0,3,4][slot-1];if(weapon===undefined)return;input.weapon=weapon;input.reload=false;resetScope();mouseAim=false;}
function cycleWeapon(direction=1){const p=me();if(!p?.alive)return;const slots=[p.primaryWeapon??0,3,4],index=Math.max(0,slots.indexOf(input.weapon));equipSlot((index+direction+3)%3+1);}
function closeLoadout(captureMouse=true){buyOpen=false;$('#loadout').hidden=true;neutral();if(captureMouse&&active&&!paused)capture();}
function openLoadout(){if(!active||paused)return;if(buyOpen){closeLoadout();return;}if(!canBuy(me())){notice('回到己方出生区，按 B 更换主武器');return;}buyOpen=true;resetScope();neutral();$('#loadout').hidden=false;for(const b of document.querySelectorAll('[data-primary]')){const chosen=Number(b.dataset.primary)===(me()?.primaryWeapon??0);b.classList.toggle('selected',chosen);b.setAttribute('aria-pressed',String(chosen));}if(document.pointerLockElement)document.exitPointerLock();$('#loadout-close').focus();}
function choosePrimary(weapon){if(!buyOpen||!canBuy(me())||![0,1,2].includes(weapon)){closeLoadout();notice('只能在己方出生区更换主武器');return;}closeLoadout();input.primaryWeapon=weapon;input.weapon=weapon;notice(`${WEAPONS[weapon].name} 已选择`,1.3);}
function rightPress(){const p=me();if(p?.weapon===2){if(p.reloadUntil>snapshot.time)return;scopeLevel=(scopeLevel+1)%3;resumeScope=0;scopeResumeAt=0;input.aim=scopeLevel>0;mouseAim=false;}else mouseAim=true;}
function applyQuality(){view?.setQuality($('#quality').value);savePrefs();}
function setMode(value){mode=value;document.querySelectorAll('[data-mode]').forEach(b=>{const selected=b.dataset.mode===mode;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected))});$('#offline-options').hidden=mode!=='offline';$('#lan-options').hidden=mode!=='lan';$('#start').hidden=mode==='lan'||active;status(mode==='offline'?'浏览器本地 AI · 无需账号和联机服务':'在 Windows 开服后，从开服地址创建或加入房间。');}
function pause(){if(!active)return;paused=true;closeLoadout(false);resetScope();neutral();$('#menu').hidden=false;$('#resume').hidden=false;$('#start').hidden=true;$('#session-actions').hidden=false;$('#panel-caption').textContent='战术菜单';$('#invite').hidden=!room;$('#restart').disabled=Boolean(room&&hostId!==selfId);$('#scoreboard').hidden=true;$('#touch-controls').hidden=true;if(document.pointerLockElement)document.exitPointerLock();}
async function capture(){if(mobile)return;try{await canvas.requestPointerLock();lockFallback=false}catch{lockFallback=true;notice('鼠标锁定不可用：按住左键拖动转向，F 开火',5)}}
async function resume(){if(!active||snapshot?.status==='ended')return;await audio.unlock();paused=false;neutral();$('#menu').hidden=true;$('#scoreboard').hidden=true;$('#touch-controls').hidden=!mobile;await capture();}
function enter(s,id){snapshot=s;selfId=id;active=true;paused=false;lastEvent=Math.max(-1,...(s.events||[]).map(e=>e.seq));view.lastEvent?.clear();for(const e of s.events||[])view.lastEvent?.add(e.seq);lastResult=false;lastTime=s.time;accumulator=0;closeLoadout(false);resetScope();delete input.primaryWeapon;lastAlive=true;audio.lastWeapon=-1;neutral();input.weapon=me()?.weapon??0;input.yaw=me()?.yaw??0;input.pitch=me()?.pitch??0;$('#hud').hidden=false;$('#menu').hidden=true;$('#touch-controls').hidden=!mobile;$('#killfeed').replaceChildren();$('#scoreboard').hidden=true;savePrefs();capture();}
async function startOffline(){try{client?.disconnect();client=null;room=null;hostId=null;await audio.unlock();match=new Match({size:Number($('#size').value),goal:Number($('#goal').value),duration:300,difficulty:$('#difficulty').value});const p=match.addHuman($('#nickname').value.trim()||'新兵',team);enter(match.snapshot(),p.id);$('#network-state').textContent='本地人机';}catch(e){status('无法进入战场：'+e.message,true)}}
function receive(s){
 const newRound=s.time<lastTime-.1||(s.events||[]).some(e=>e.type==='restart'&&e.seq>lastEvent);
 if(newRound){lastResult=false;closeLoadout(false);resetScope();delete input.primaryWeapon;$('#killfeed').replaceChildren();$('#scoreboard').hidden=true;$('#menu').hidden=true;paused=false;audio.lastWeapon=-1;view.resetView();view.cameraReady=false;}
 lastTime=s.time;snapshot=s;const p=me();
 if(p){if(newRound||(!lastAlive&&p.alive)){neutral();resetScope();input.weapon=newRound?(p.weapon??p.primaryWeapon??0):(p.primaryWeapon??0);input.yaw=p.yaw;input.pitch=p.pitch;delete input.primaryWeapon;}if(!p.alive){resetScope();if(buyOpen)closeLoadout(false);}lastAlive=p.alive;}
}
async function getClient(){await audio.unlock();if(client)return client;const health=await fetch('/api/fps/health',{signal:AbortSignal.timeout(3500)}).catch(()=>null);if(!health?.ok)throw new Error('当前地址没有局域网服务。请双击 start-fps-lan.cmd，并使用开服窗口中的地址。');client=new LanClient({onJoined:data=>{match=null;room=data.roomId;hostId=data.hostId;enter(data.snapshot,data.playerId);$('#network-state').textContent='局域网 · '+room.slice(0,6);status('房间已就绪，空位由 AI 补齐。');},onSnapshot:(data,envelope)=>{if(envelope?.hostId)hostId=envelope.hostId;receive(data);},onRoom:data=>{hostId=data.hostId;},onError:e=>status(typeof e==='string'?e:e.message||'联机失败',true),onClose:()=>{if(!room)return;neutral();active=false;paused=true;room=null;client=null;$('#hud').hidden=true;$('#menu').hidden=false;$('#resume').hidden=true;$('#session-actions').hidden=true;$('#start').hidden=true;$('#touch-controls').hidden=true;status('连接已断开。请检查开服电脑，再重新加入房间；原位置已由 AI 接管。',true);},onRooms:rooms=>renderRooms(rooms)});await client.connect();client.listRooms();return client;}
async function lan(action){status('正在连接开服电脑…');try{const c=await getClient();if(action==='create')c.create({name:$('#nickname').value.trim()||'新兵',size:Number($('#size').value),goal:Number($('#goal').value),difficulty:$('#difficulty').value});else{const code=$('#room-code').value.trim();if(!code)throw new Error('填写好友给你的房间邀请码。');c.join(code,$('#nickname').value.trim()||'新兵');}}catch(e){client?.disconnect();client=null;status(e.message,true);}}
function renderRooms(rooms){$('#room-list').replaceChildren();for(const r of rooms||[]){const b=document.createElement('button');b.textContent=`${r.roomId?.slice(0,6)||r.id?.slice(0,6)} · ${r.size}v${r.size} · ${r.humans??r.humanCount??0} 位玩家`;b.onclick=()=>{$('#room-code').value=r.roomId||r.id;lan('join')};$('#room-list').append(b);}}
function leave(){const c=client;room=null;client=null;c?.leave();c?.disconnect();match=null;snapshot=null;selfId=null;active=false;paused=true;closeLoadout(false);resetScope();delete input.primaryWeapon;neutral();document.body.classList.remove('is-dead');if(document.pointerLockElement)document.exitPointerLock();$('#hud').hidden=true;$('#menu').hidden=false;$('#resume').hidden=true;$('#session-actions').hidden=true;$('#scoreboard').hidden=true;$('#touch-controls').hidden=true;$('#invite-info').hidden=true;$('#panel-caption').textContent='开始对战';setMode(mode);}
async function restart(){if(room){if(hostId!==selfId){notice('只有房主可以重开');return}client.restart();await resume();}else if(match){match.restart();const p=match.players.find(p=>p.id===selfId);enter(match.snapshot(),p.id);await audio.unlock();}}
async function invite(){if(!room)return;try{const r=await fetch(`/api/fps/invites?room=${encodeURIComponent(room)}`);const data=await r.json();const links=data.links||data.urls||[...(data.lan||[]),data.local].filter(Boolean);const strings=links.map(x=>typeof x==='string'?x:x.url);const url=strings.find(x=>!x.includes('127.0.0.1')&&!x.includes('localhost'))||strings[0]||`${location.origin}${location.pathname}?room=${encodeURIComponent(room)}`;const text=`运输船 · ${snapshot?.size||$('#size').value}v${snapshot?.size||$('#size').value}\n${url}\n邀请码：${room}\n同一局域网打开链接，即可加入；空位由 AI 补齐。`;$('#invite-text').value=text;$('#invite-info').hidden=false;try{await navigator.clipboard.writeText(text);status('邀请信息已复制，请自行发给好友。')}catch{$('#invite-text').focus();$('#invite-text').select();status('邀请信息已生成，请按 Ctrl+C 复制。')}}catch(e){status('生成邀请失败：'+e.message,true)}}
function processEvents(){if(!snapshot)return;for(const e of snapshot.events||[]){if(e.seq<=lastEvent)continue;lastEvent=e.seq;const p=me();view.event(e,selfId);audio.event(e,p,snapshot.players);if(e.type==='shot'&&e.playerId===selfId&&e.weapon===2&&scopeLevel){resumeScope=scopeLevel;scopeLevel=0;input.aim=false;scopeResumeAt=performance.now()+WEAPONS[2].interval*1000;}if(e.type==='hit'&&e.playerId===selfId)hitUntil=performance.now()+140;if(e.type==='hit'&&e.targetId===selfId)damageUntil=performance.now()+300;if(e.type==='kill'){killFeed(e,snapshot.players,selfId);if(e.playerId===selfId)notice(e.headshot?'爆头击杀':'击杀确认',1.1);}}}
function updateRadar(){
 const c=$('#radar').getContext('2d'),w=170;c.clearRect(0,0,w,w);c.fillStyle='#16323d';c.fillRect(0,0,w,w);
 const width=MAP.bounds.maxX-MAP.bounds.minX,length=MAP.bounds.maxZ-MAP.bounds.minZ,scale=145/Math.max(width,length);
 const px=x=>w/2+x*scale,pz=z=>w/2+z*scale;
 c.fillStyle='#28444c';c.fillRect(px(MAP.bounds.minX),pz(MAP.bounds.minZ),width*scale,length*scale);
 for(const b of MAP.boxes){if(b.kind==='deck'||b.kind.startsWith('tunnel-')||b.kind==='tunnel-roof')continue;
  c.save();c.translate(px(b.x),pz(b.z));c.rotate(-(b.yaw||0));c.fillStyle=b.kind==='cargo'?'#66765e':b.kind==='crate'?'#aa8d5e':'#758e8890';c.fillRect(-b.w*scale/2,-b.d*scale/2,b.w*scale,b.d*scale);c.restore();
 }
 c.strokeStyle='#82a99a90';c.setLineDash([2,2]);for(const t of MAP.tunnels){c.beginPath();c.moveTo(px(t.x),pz(t.baseZ));c.lineTo(px(t.x),pz(t.exitZ));c.stroke();}c.setLineDash([]);
 const p=me();for(const a of snapshot.players){if(!a.alive||a.team!==p?.team)continue;c.fillStyle=a.id===selfId?'#f5db8e':a.team===0?'#87ccec':'#ebba8e';c.beginPath();c.arc(px(a.x),pz(a.z),a.id===selfId?3.2:2,0,Math.PI*2);c.fill();if(a.id===selfId){c.strokeStyle='#fff1c4';c.beginPath();c.moveTo(px(a.x),pz(a.z));c.lineTo(px(a.x-Math.sin(input.yaw)*2.5),pz(a.z-Math.cos(input.yaw)*2.5));c.stroke();}}
}
function drawRoster(result=false){if(!snapshot)return;const mine=me();$('#result-title').textContent=result?(snapshot.winner===null||snapshot.winner===undefined?'平局':snapshot.winner===mine?.team?'胜利 · 甲板已控制':'战败 · 下局再战'):'本局战绩';$('#result-score').textContent=snapshot.score.join(' : ');const rosters=$('#rosters');rosters.replaceChildren();for(let t=0;t<2;t++){const section=document.createElement('section');section.className='roster'+(t===1?' orange':'');const h=document.createElement('h3');h.textContent=t===0?'保卫者 / DEFENDERS':'潜伏者 / RAIDERS';const table=document.createElement('table');table.innerHTML='<thead><tr><th>呼号</th><th>击杀</th><th>阵亡</th><th>K/D</th></tr></thead>';const body=document.createElement('tbody');for(const p of snapshot.players.filter(p=>p.team===t).sort((a,b)=>b.kills-a.kills)){const tr=document.createElement('tr');if(p.id===selfId)tr.className='self';const td=document.createElement('td');td.textContent=p.name+(p.id===selfId?' ◂':'');if(p.bot){const bot=document.createElement('span');bot.className='bot-tag';bot.textContent=' [AI]';td.append(bot)}tr.append(td);for(const v of [p.kills,p.deaths,(p.kills/Math.max(1,p.deaths)).toFixed(1)]){const cell=document.createElement('td');cell.textContent=v;tr.append(cell)}body.append(tr)}table.append(body);section.append(h,table);rosters.append(section)}$('#result-actions').hidden=!result;$('#result-restart').disabled=Boolean(room&&hostId!==selfId);}
function updateHUD(now){if(!snapshot)return;const p=me();if(!p)return;$('#score-blue').textContent=snapshot.score[0];$('#score-orange').textContent=snapshot.score[1];const remaining=Math.max(0,(snapshot.duration??300)-snapshot.time);$('#clock').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(Math.floor(remaining%60)).padStart(2,'0')}`;$('#goal-label').textContent=`先到 ${snapshot.goal??$('#goal').value} 分`;$('#health').textContent=Math.ceil(p.hp);$('#health-fill').style.width=p.hp+'%';$('#team-label').textContent=p.team===0?'保卫者 / DEFENDER':'潜伏者 / RAIDER';const gun=WEAPONS[p.weapon];$('#weapon-name').textContent=gun?.name||'M4A1-S';$('#ammo-line').hidden=p.weapon===4;$('#ammo').textContent=p.ammo[p.weapon];$('#reserve').textContent=p.reserve[p.weapon];$('#reload-state').textContent=p.weapon===4?'左键轻刀 · 右键重刀':p.reloadUntil>snapshot.time?`装弹中 · ${(p.reloadUntil-snapshot.time).toFixed(1)}s`:canBuy(p)?'B 选择主武器 · R 换弹':'R 换弹';updateEquipment(p);updateDeath(p,snapshot.players,snapshot.time);$('#crosshair').hidden=!p.alive||paused||buyOpen||(scopeLevel>0&&p.weapon===2);$('#crosshair').classList.toggle('aim',input.aim);scopeOverlay(scopeLevel,p,paused||buyOpen);$('#performance').textContent=`${Math.round(view.stats?.fps||0)} FPS · ${$('#quality').selectedOptions[0].text}`;updateRadar();if(buyOpen&&!canBuy(p))closeLoadout(false);if(!$('#scoreboard').hidden)drawRoster(snapshot.status==='ended');if(snapshot.status==='ended'&&!lastResult){lastResult=true;paused=true;closeLoadout(false);resetScope();neutral();$('#menu').hidden=true;$('#scoreboard').hidden=false;$('#touch-controls').hidden=true;drawRoster(true);if(document.pointerLockElement)document.exitPointerLock();}if(p.shieldUntil>snapshot.time&&p.alive&&!paused&&!buyOpen)notice('出生保护 · B 选择主武器',.15);}
function sampleInput(){if(paused||buyOpen){input.forward=0;input.strafe=0;input.fire=false;input.altFire=false;input.aim=false;return}const p=me();input.forward=touch.forward||(Number(keys.has('KeyW')||keys.has('ArrowUp'))-Number(keys.has('KeyS')||keys.has('ArrowDown')));input.strafe=touch.strafe||(Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft')));input.walk=keys.has('ShiftLeft')||keys.has('ShiftRight');input.crouch=keys.has('ControlLeft')||keys.has('ControlRight');input.jump=keys.has('Space')||touch.jump;input.fire=mouseFire||touch.fire||keys.has('KeyF');input.altFire=p?.weapon===4&&(mouseAim||touch.aim);input.aim=p?.weapon===2?scopeLevel>0:p?.weapon===4?false:mouseAim||touch.aim;}
let mouseFire=false,mouseAim=false,dragging=false,dragX=0,dragY=0;
function turn(dx,dy){if(paused||buyOpen||!active)return;const sens=scopeLevel===2?.00028:input.aim?.001:.0024;input.yaw-=dx*sens;input.pitch=Math.max(-1.45,Math.min(1.45,input.pitch-dy*sens));}
window.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea')||!active)return;if(['Space','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ControlLeft','ControlRight','KeyB','Digit1','Digit2','Digit3','Digit4'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(buyOpen)closeLoadout();else if(!paused)pause();return;}if(paused)return;if(e.code==='KeyB'&&!e.repeat){openLoadout();return;}if(buyOpen){if(/^Digit[1-3]$/.test(e.code)&&!e.repeat)choosePrimary(Number(e.code.slice(-1))-1);return;}keys.add(e.code);if(e.code==='KeyR'){input.reload=true;resetScope();}if(/^Digit[1-3]$/.test(e.code)&&!e.repeat)equipSlot(Number(e.code.slice(-1)));if(e.code==='Tab'){$('#scoreboard').hidden=false;drawRoster();}});
window.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Tab'&&snapshot?.status!=='ended')$('#scoreboard').hidden=true;});
canvas.addEventListener('mousedown',e=>{if(paused||buyOpen||!active)return;if(document.pointerLockElement!==canvas&&!lockFallback){capture();return}if(e.button===0){if(lockFallback){dragging=true;dragX=e.clientX;dragY=e.clientY}else mouseFire=true;}if(e.button===2)rightPress();});
window.addEventListener('mouseup',e=>{if(e.button===0){mouseFire=false;dragging=false}if(e.button===2)mouseAim=false;});
window.addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas)turn(e.movementX,e.movementY);else if(lockFallback&&dragging){turn(e.clientX-dragX,e.clientY-dragY);dragX=e.clientX;dragY=e.clientY;}});
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{if(active&&!paused&&!buyOpen){e.preventDefault();cycleWeapon(e.deltaY>0?1:-1);}},{passive:false});
document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&active&&!paused&&!buyOpen&&!lockFallback&&snapshot?.status!=='ended')pause();});
window.addEventListener('blur',()=>{mouseFire=false;mouseAim=false;neutral();if(match&&active&&!paused)pause();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){mouseFire=false;mouseAim=false;neutral();if(match&&active)pause();}});
window.addEventListener('message',e=>{if(e.data?.type==='ai-game-lab:pause'&&match&&active)pause();});
function bindPad(selector,move){const pad=$(selector);let origin=null;pad.addEventListener('pointerdown',e=>{e.preventDefault();origin={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY};pad.setPointerCapture(e.pointerId)});pad.addEventListener('pointermove',e=>{if(!origin)return;e.preventDefault();if(move){touch.strafe=Math.max(-1,Math.min(1,(e.clientX-origin.x)/35));touch.forward=Math.max(-1,Math.min(1,(origin.y-e.clientY)/35));}else{turn((e.clientX-origin.lastX)*1.6,(e.clientY-origin.lastY)*1.6);origin.lastX=e.clientX;origin.lastY=e.clientY;}});const end=()=>{origin=null;if(move){touch.strafe=0;touch.forward=0;}};pad.addEventListener('pointerup',end);pad.addEventListener('pointercancel',end);}
bindPad('#move-pad',true);bindPad('#look-pad',false);
for(const [id,key] of [['touch-fire','fire'],['touch-aim','aim'],['touch-jump','jump']]){const b=$('#'+id);b.addEventListener('pointerdown',e=>{e.preventDefault();touch[key]=true;b.setPointerCapture(e.pointerId)});for(const end of ['pointerup','pointercancel'])b.addEventListener(end,()=>touch[key]=false);}
$('#touch-aim').addEventListener('pointerdown',()=>{if(me()?.weapon===2)rightPress();});$('#touch-reload').onclick=()=>{input.reload=true;resetScope();};$('#touch-weapon').onclick=()=>cycleWeapon();$('#touch-buy').onclick=openLoadout;
for(const b of document.querySelectorAll('[data-primary]'))b.onclick=()=>choosePrimary(Number(b.dataset.primary));$('#loadout-close').onclick=()=>closeLoadout();for(const b of document.querySelectorAll('[data-equip-slot]'))b.onclick=()=>{if(!paused&&!buyOpen)equipSlot(Number(b.dataset.equipSlot));};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{team=Number(b.dataset.team);document.querySelectorAll('[data-team]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))})});
$('#start').onclick=startOffline;$('#resume').onclick=resume;$('#menu-button').onclick=pause;$('#quality').onchange=applyQuality;$('#restart').onclick=restart;$('#result-restart').onclick=restart;$('#result-menu').onclick=()=>{$('#scoreboard').hidden=true;pause()};$('#leave').onclick=leave;$('#invite').onclick=invite;$('#create-room').onclick=()=>lan('create');$('#join-room').onclick=()=>lan('join');
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{notice('可按 F11 使用浏览器全屏',4)}};
window.addEventListener('resize',()=>view?.resize());
function frame(now){const dt=Math.min(.08,(now-frameTime)/1000);frameTime=now;if(resumeScope&&now>=scopeResumeAt&&me()?.alive&&me()?.weapon===2&&!paused&&!buyOpen){scopeLevel=resumeScope;resumeScope=0;}sampleInput();if(match&&active&&!paused&&snapshot?.status==='playing'){accumulator=Math.min(.15,accumulator+dt);while(accumulator>=1/60){match.input(selfId,combatInput());match.step(1/60);input.reload=false;delete input.primaryWeapon;accumulator-=1/60;}receive(match.snapshot());}if(client&&active&&now-lastNet>33){if(client.sendInput(combatInput())){input.reload=false;delete input.primaryWeapon;}lastNet=now;}if(active){processEvents();const p=me();audio.syncWeapon(p);if(p?.alive&&!paused&&!buyOpen)audio.footsteps(now/1000,p.grounded&&Math.hypot(p.vx,p.vz)>.2,p.walking||p.crouching);if(now-lastHud>100){updateHUD(now);lastHud=now;}}view.render(snapshot||{time:now/1000,players:[],score:[0,0],events:[]},active?selfId:null,{...input,zoomLevel:scopeLevel,paused},dt);$('#notice').style.opacity=now<noticeUntil&&!paused?'1':'0';$('#hitmarker').style.opacity=now<hitUntil?'1':'0';$('#damage-flash').style.opacity=now<damageUntil?String((damageUntil-now)/500):'0';requestAnimationFrame(frame);}
let initializing=false,renderLoopStarted=false;
async function initializeArena(){
 if(initializing)return;initializing=true;loadingScreen.begin();loadingScreen.onRetry(initializeArena);assetLoading.resetFailed();
 let creatingRenderer=false;
 try{
  loadingScreen.stage('下载人物、枪械与配套动作…');await Promise.all([loadCharacters(),loadViewModels()]);
  audio.prepare({retryFailed:true});loadingScreen.stage('准备运输船甲板与贴图…');
  if(!view){creatingRenderer=true;view=new ArenaRenderer(canvas,{quality:$('#quality').value});creatingRenderer=false;}else view.retryEnvironment();
  await view.ready;loadingScreen.complete();if(!renderLoopStarted){renderLoopStarted=true;frameTime=performance.now();requestAnimationFrame(frame);}
  const query=new URLSearchParams(location.search);if(!staticMode&&query.has('room')){setMode('lan');$('#room-code').value=query.get('room');status('好友邀请已填好，输入呼号后点击“加入房间”。');}
  if(query.has('qa')&&!window.__freight)Object.defineProperty(window,'__freight',{value:{get snapshot(){return snapshot},get localId(){return selfId},get match(){return match},get input(){return input},get view(){return view},get audio(){return audio},get paused(){return paused},get zoomLevel(){return scopeLevel},get buyOpen(){return buyOpen},get loading(){return assetLoading.snapshot},pause,resume,restart,startOffline,leave}});
 }catch(error){loadingScreen.fail(error,{webgl:creatingRenderer});console.error(error);}
 finally{initializing=false;}
}
await initializeArena();
